# Generated by Django 5.1.5 on 2025-01-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama_kategori',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='produk',
            name='nama_produk',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='nama_status',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
