# Generated by Django 5.1.5 on 2025-01-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_alter_kategori_nama_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama_kategori',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='nama_status',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
