# Generated by Django 5.1.5 on 2025-01-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_alter_kategori_nama_kategori_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name': 'Produk', 'verbose_name_plural': 'Produk'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='status',
            name='nama_status',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='produk.singer')),
            ],
        ),
    ]
